import { Color } from './colors'

export const technologies = {
  Flutter: { title: 'Flutter', color: Color.lightBlue },
  Riverpod: { title: 'Riverpod', color: Color.darkBlue },
  SpringBoot: { title: 'Spring Boot', color: Color.darkPurple },
  MongoDB: { title: 'MongoDB', color: Color.lightBlue },
  Express: { title: 'Express', color: Color.darkBlue },
  React: { title: 'React', color: Color.darkPurple },
  Node: { title: 'Node', color: Color.purple },
  Kotlin: { title: 'Kotlin', color: Color.lightBlue },
  Compose: { title: 'Compose', color: Color.darkBlue },
  Java: { title: 'Java', color: Color.purple },
  Android: { title: 'Android', color: Color.lightBlue },
  Cpp: { title: 'C++', color: Color.darkBlue },
  C: { title: 'C', color: Color.darkPurple },
  NET: { title: '.NET', color: Color.purple },
  Swift: { title: 'Swift', color: Color.lightBlue },
  Razor: { title: 'Razor', color: Color.darkBlue },
  Knockout: { title: 'Knockout.js', color: Color.darkPurple },
  Ssms: { title: 'SSMS', color: Color.purple },
  Bootstrap: { title: 'Bootstrap', color: Color.lightBlue },
  Tailwind: { title: 'Tailwind', color: Color.darkBlue },
  CSharp: { title: 'C#', color: Color.darkPurple },
  Unity: { title: 'Unity', color: Color.purple },
  Figma: { title: 'Figma', color: Color.lightBlue },
  Vue: { title: 'Vue', color: Color.darkBlue },
  Angular: { title: 'Angular', color: Color.darkPurple },
  Python: { title: 'Python', color: Color.purple },
  Pygame: { title: 'Pygame', color: Color.lightBlue },
  Numpy: { title: 'Numpy', color: Color.darkBlue },
  Scipy: { title: 'Scipy', color: Color.darkPurple },
  Skimage: { title: 'Skimage', color: Color.purple },
  Matplotlib: { title: 'Matplotlib', color: Color.lightBlue },
  Jupyter: { title: 'Jupyter', color: Color.darkBlue },
  Osmnx: { title: 'Osmnx', color: Color.darkPurple },
  NetworkX: { title: 'NetworkX', color: Color.purple },
  Firebase: { title: 'Firebase', color: Color.lightBlue },
  Docker: { title: 'Docker', color: Color.darkBlue },
  Sass: { title: 'Sass', color: Color.darkPurple },
  SparkJava: { title: 'Spark Java', color: Color.purple },
  Jooq: { title: 'Jooq', color: Color.lightBlue },
  TypeScript: { title: 'TypeScript', color: Color.darkBlue },
  Html: { title: 'HTML', color: Color.darkPurple },
  Css: { title: 'CSS', color: Color.purple },
  Javascript: { title: 'Javascript', color: Color.lightBlue },
  Jquery: { title: 'Jquery', color: Color.darkBlue },
  Ajax: { title: 'Ajax', color: Color.darkPurple },
  Aspose: { title: 'Aspose', color: Color.purple },
  Next: { title: 'Next', color: Color.purple },
  Scala: { title: 'Scala', color: Color.purple },
}
