import { Color } from './colors'

export const technologies = {
  Flutter: { title: 'Flutter', color: '#60BBE3' },
  Riverpod: { title: 'Riverpod', color: Color.darkBlue },
  SpringBoot: { title: 'Spring Boot', color: '#67AA3C' },
  MongoDB: { title: 'MongoDB', color: '#54A14C' },
  Express: { title: 'Express', color: '#3B7F3A' },
  React: { title: 'React', color: Color.darkBlue },
  Node: { title: 'Node', color: '#54A14C' },
  Kotlin: { title: 'Kotlin', color: Color.lightBlue },
  Compose: { title: 'Compose', color: Color.darkBlue },
  Java: { title: 'Java', color: '#DE2B2C' },
  Android: { title: 'Android', color: '#9CC036' },
  Cpp: { title: 'C++', color: Color.darkBlue },
  C: { title: 'C', color: Color.darkPurple },
  NET: { title: '.NET', color: Color.purple },
  Swift: { title: 'Swift', color: Color.lightBlue },
  Razor: { title: 'Razor', color: Color.darkBlue },
  Knockout: { title: 'Knockout.js', color: Color.darkPurple },
  Ssms: { title: 'SSMS', color: Color.purple },
  Bootstrap: { title: 'Bootstrap', color: Color.lightBlue },
  Tailwind: { title: 'Tailwind', color: Color.darkBlue },
  CSharp: { title: 'C#', color: Color.darkPurple },
  Unity: { title: 'Unity', color: '#7A7A7A' },
  Figma: { title: 'Figma', color: Color.lightBlue },
  Vue: { title: 'Vue', color: Color.darkBlue },
  Angular: { title: 'Angular', color: Color.darkPurple },
  Python: { title: 'Python', color: '#517BA0' },
  Pygame: { title: 'Pygame', color: '#F2CB33' },
  Numpy: { title: 'Numpy', color: Color.darkBlue },
  Scipy: { title: 'Scipy', color: Color.darkPurple },
  Skimage: { title: 'Skimage', color: Color.purple },
  Matplotlib: { title: 'Matplotlib', color: Color.lightBlue },
  Jupyter: { title: 'Jupyter', color: Color.darkBlue },
  Osmnx: { title: 'Osmnx', color: Color.darkPurple },
  NetworkX: { title: 'NetworkX', color: Color.purple },
  Firebase: { title: 'Firebase', color: '#F2C12C' },
  Docker: { title: 'Docker', color: '#1197D0' },
  Sass: { title: 'Sass', color: Color.darkPurple },
  SparkJava: { title: 'Spark Java', color: Color.purple },
  Jooq: { title: 'Jooq', color: Color.lightBlue },
  TypeScript: { title: 'TypeScript', color: '#2F72BC' },
  Html: { title: 'HTML', color: Color.darkPurple },
  Css: { title: 'CSS', color: Color.purple },
  Javascript: { title: 'Javascript', color: Color.lightBlue },
  Jquery: { title: 'Jquery', color: Color.darkBlue },
  Ajax: { title: 'Ajax', color: Color.darkPurple },
  Aspose: { title: 'Aspose', color: Color.purple },
  Next: { title: 'Next', color: '#7CD3D4' },
  Scala: { title: 'Scala', color: '#D33121' },
  AzureML: { title: 'Azure ML', color: '#2c97ec' },
  AzureDataFactory: { title: 'Azure Data Factory', color: '#0078D4' },
  CustomVision: { title: 'Custom Vision', color: '#0e426c' },
}
