import { Color } from './colors'

export const technologies = {
  Flutter: { title: 'Flutter', color: Color.lightBlue },
  Riverpod: { title: 'Riverpod', color: Color.darkBlue },
  SpringBoot: { title: 'Spring Boot', color: Color.darkPurple },
  MongoDB: { title: 'MongoDB', color: Color.lightBlue },
  Express: { title: 'Express', color: Color.darkBlue },
  React: { title: 'React', color: Color.darkPurple },
  Node: { title: 'Node', color: Color.purple },
  Kotlin: { title: 'Kotlin', color: Color.lightBlue },
  Compose: { title: 'Compose', color: Color.darkBlue },
  Java: { title: 'Java', color: Color.purple },
  Android: { title: 'Android', color: Color.lightBlue },
  Cpp: { title: 'C++', color: Color.darkBlue },
  C: { title: 'C', color: Color.darkPurple },
  NET: { title: '.NET', color: Color.purple },
  Swift: { title: 'Swift', color: Color.lightBlue },
  Razor: { title: 'Razor', color: Color.darkBlue },
  Knockout: { title: 'Knockout.js', color: Color.darkPurple },
  Ssms: { title: 'SSMS', color: Color.purple },
  Bootstrap: { title: 'Bootstrap', color: Color.lightBlue },
  Tailwind: { title: 'Tailwind', color: Color.darkBlue },
  CSharp: { title: 'C#', color: Color.darkPurple },
  Unity: { title: 'Unity', color: Color.purple },
  Figma: { title: 'Figma', color: Color.lightBlue },
  Vue: { title: 'Vue', color: Color.darkBlue },
  Angular: { title: 'Angular', color: Color.darkPurple },
  Python: { title: 'Python', color: Color.purple },
  Pygame: { title: 'Pygame', color: Color.lightBlue },
}
